'''
some configs for hadoop
'''

blockFileName = 'block.txt'
blendFileName = 'blend.txt'
argFileName = 'arg.txt'
labelFileName = 'label.txt'
planeFileName = 'plane.txt'
bundleFileName = 'bundle.out'
finalFileName = 'final.jpg'
configFileName = 'conf'
coorFileName = 'coor.txt'
adjFileName = 'ad.txt'
bundlerFileName = 'RunBundler.sh'
argFileName = 'arg.txt'

imageFilePath = '/home/mfkiller/stitch/src/cloudComputing/image.py'
blendFilePath = '/home/mfkiller/stitch/src/cloudComputing/blend.py'
labelFilePath = '/home/mfkiller/stitch/src/cloudComputing/label.py'
configFilePath = '/home/mfkiller/stitch/src/cloudComputing/config.py'

fileSuffix = '.zip'
hdfsFolder = '/home/mfkiller/stitch/hdfs/'
cloudsrcFolder = '/home/mfkiller/stitch/src/cloudComputing/'
bundlersrcFolder = '/home/mfkiller/stitch/src/bundler/'
logFolder = '/home/mfkiller/stitch/logs/'
